/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightfrost.reactivemytubeconsumer.client.api;

import io.nightfrost.reactivemytubeconsumer.client.model.Comment;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for CommentHandlerApi
 */
@Disabled
public class CommentHandlerApiTest {

    private final CommentHandlerApi api = new CommentHandlerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void createCommentTest()  {
        // uncomment below to test the function
        //Comment comment = null;
        //api.createComment(comment).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void deleteCommentTest()  {
        // uncomment below to test the function
        //String id = null;
        //api.deleteComment(id).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getAllByMovieIdTest()  {
        // uncomment below to test the function
        //String id = null;
        //api.getAllByMovieId(id).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getAllByUserIdTest()  {
        // uncomment below to test the function
        //String id = null;
        //api.getAllByUserId(id).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getCommentByIdTest()  {
        // uncomment below to test the function
        //String id = null;
        //api.getCommentById(id).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void updateCommentTest()  {
        // uncomment below to test the function
        //String id = null;
        //Comment comment = null;
        //api.updateComment(id, comment).block();

        // TODO: test validations
    }
    
}
