/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightfrost.reactivemytubeconsumer.client.api;

import io.nightfrost.reactivemytubeconsumer.client.model.MovieDTO;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for MovieControllerApi
 */
@Disabled
public class MovieControllerApiTest {

    private final MovieControllerApi api = new MovieControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void getAllAvailableMovies1Test()  {
        // uncomment below to test the function
        //String query = null;
        //List<MovieDTO> response = api.getAllAvailableMovies1(query).collectList().block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getMovieTest()  {
        // uncomment below to test the function
        //String id = null;
        //api.getMovie(id).block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void postMovieTest()  {
        // uncomment below to test the function
        //Object response = api.postMovie().block();

        // TODO: test validations
    }
    
}
