/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightfrost.reactivemytubeconsumer.client.api;

import io.nightfrost.reactivemytubeconsumer.client.model.MovieDTO;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.*;
import java.util.stream.Collectors;

/**
 * API tests for MovieControllerApi
 */

public class MovieControllerApiTest {

    private final MovieControllerApi api = new MovieControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void getAllAvailableMovies1Test()  {
        String query = "n";
        List<MovieDTO> response = api.getAllAvailableMovies1(query).collectList().block();

        assert !Objects.requireNonNull(response).isEmpty();
        response.stream().forEach(movieDTO -> {
           assert movieDTO.getFilename() != null && !movieDTO.getFilename().isEmpty();
        });
    }

    /**
     *
     *
     *
     */
    @Test
    public void getMovieTest()  {
        api.getMovie("668adb3ab9b443097ca6f9df").doOnError(error -> System.out.println(error.getMessage())).block();
        assert true;
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    @Disabled
    public void postMovieTest()  {
        // uncomment below to test the function
        Object response = api.postMovie().block();
    }
    
}
