/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nightfrost.reactivemytubeconsumer.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MovieDTO
 */
class MovieDTOTest {
    private final MovieDTO model = new MovieDTO();

    /**
     * Model tests for MovieDTO
     */
    @Test
    void testMovieDTO() {
        // TODO: test MovieDTO
    }

    /**
     * Test the property 'getId'
     */
    @Test
    void getIdTest() {
        // TODO: test getId
    }

    /**
     * Test the property 'filename'
     */
    @Test
    void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'uploadDate'
     */
    @Test
    void uploadDateTest() {
        // TODO: test uploadDate
    }

}
